tranfer file to server

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,19 +1,24 @@
-
 #!/usr/bin/env bash
-#Script that transfers a file from our client to a server
+#checking for cla
 
-# Check if all parameters are provided and do as it iplaned 
-if [ $# -lt 4 ]; then
-  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-  exit 1
+if [$# -lt 4]
+then 
+	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+	exit 1
 fi
-
-file_path=$1
-server_ip=$2
+# assign var
+path_to_file=$1
+ip=$2
 username=$3
-ssh_key=$4
+path_to_ssh_key=$4
 
-# Transfer the file using scp
-scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip:~/"
+#disable strict host key checking 
+scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
 
-exit 0
+#checking if the transfer was successful 
+if [$?-eq 0]
+then 
+	echo "FILE TRANSFER WAS SUCCESSFULL"
+else
+	echo "FILE TRANSFER FAILED"
+fi
